### ISSUE TITLE
Rest API fails when serving with uvicorn locally

### ISSUE THREAD

**Issue by david-saeger** [awslabs/LISA#62]
Following the directions in the docs [here](https://github.com/awslabs/LISA?tab=readme-ov-file#run-rest-api-locally) uvicorn fails when trying to load os.environ["LITELLM_KEY"] 

litellm_passthrough.py seems to indicate that a LiteLLM key is necessary  to passthrough for requests for the LiteLLM database. Is this necessary for local testing development? Should it be added to the docs that this key is a cross dependency?

**Comment by petermuller** [comment]
Ah sorry about that- we're actively developing new features in the "develop" branch, but since that's the default branch, that's what a clone will grab. Please use the "main" branch https://github.com/awslabs/LISA/tree/main and that should get you out of that situation and onto our stable release.

if you'd like to continue on the bleeding edge of the development branch, then just make sure that the LITELLM_KEY environment variable is set to the value that you put in your config.yaml file:
* https://github.com/awslabs/LISA/blob/5ff23fff9275d52bec36b9ef36edec6e1d4b51a9/lib/schema.ts#L788-L792
* https://github.com/awslabs/LISA/blob/5ff23fff9275d52bec36b9ef36edec6e1d4b51a9/test/cdk/mocks/config.yaml#L237-L239
